arena:
  # ВРЕМЕННО НЕ РАБОТАЕТ. Координаты центра арены (где появляются игроки при входе)
  spawn:
    x: 0
    y: 100
    z: 0
    world: world

  # Координаты позиций для игроков при начале дуэли
  player1:
    x: -10
    y: 100
    z: 0
    world: world

  player2:
    x: 10
    y: 100
    z: 0
    world: world

# Настройки игры
game:
  countdown: 5 # Обратный отсчёт до начала (сек)
  duration: 60 # ВРЕМЕННО НЕ РАБОТАЕТ. Не ставить > 60, либо будет баг с боссбаром или вообще не будет работать (временно)
  arena-close-delay: 10 # Задержка перед закрытием арены (сек)